### ISSUE TITLE
sqls -> sqlls

### ISSUE THREAD

**Issue by will** [dundalek/lazy-lsp.nvim#16]
sqls has been archived on GitHub https://github.com/lighttiger2505/sqls

So lsp-config has marked it deprecated https://github.com/neovim/nvim-lspconfig/pull/2544 which splashes a warning message each time you start nvim. 

They recommend using "sqlls" https://github.com/joe-re/sql-language-server instead, but I don't see a nix package for it yet unfortunately. 

I tried adding it to `excluded_servers` but it still pops up the warning. It'd be nice if there was a way to just ignore it, but I'm not sure what to try. Do you have any ideas?

**Comment by dundalek** [comment]
It sounds to me we should make the `excluded_servers` option work to prevent the warning. It might be a simple fix to just flip a condition, I will look into that.

I wonder if we should also remove `sqls` now to reduce noise so that people would not even need to add the exclusion to suppress the warning? What do you think?

In the future it might be nice to have a custom Flake, so we could use servers that are not yet packaged in nixpkgs. But I will probably wait with that until flakes are marked as a stable feature.

**Comment by dundalek** [comment]
Fixed in https://github.com/dundalek/lazy-lsp.nvim/commit/1e9aa30df98d5bef804e252b2afde2a4f5fc50e1, adding it to `excluded_servers` will prevent the warning now.

**Comment by will** [comment]
Confirm that 1e9aa30 fixes the problem, thanks!

It's hard to say with removing it or not. I don't have a good feeling for how many people update all their plugins all the time like me, or stick to released versions, or what.

A custom flake could be cool for sure, but the amount of work kinda seems daunting!

**Comment by kamalmarhubi** [comment]
🤦 I didn't understand why this wasn't working for me... turned out it was this:

```patch
diff --git i/files/nvim/lua/config/init.lua w/files/nvim/lua/config/init.lua
index d9ba516..941e6fa 100644
--- i/files/nvim/lua/config/init.lua
+++ w/files/nvim/lua/config/init.lua
@@ -30,7 +30,7 @@ require('lazy-lsp').setup {
     "jedi_language_server",
     "ltex",
     "pylsp",
-    "slqs",
+    "sqls",
   },
   default_config = {
     on_attach = function(client, buffnr)
```
