### ISSUE TITLE
Consider taking `PATH` into account

### ISSUE THREAD

**Issue by metiulekm** [dundalek/lazy-lsp.nvim#22]
I think that launching the client directly if it can be found in `PATH` might be a good idea. I can think of a couple of usecases:
1. This way, people who need to install some servers manually for some reason can still configure them using your plugin. Right now, they need to configure them using nvim-lspconfig and then tell your plugin to not configure them, which adds some duplication (or at least LoC).
2. Some people might use a different copy of the language server for a project. AFAIK this is quite common in Haskell for example, since HLS is tightly bound to the compiler. Therefore sometimes Haskell projects which provide a Nix shell also add the correct build of HLS to the development shell (example: <https://github.com/fjvallarino/monomer/blob/05c5d6c9b5d0649ad5da59b67cb0328fe82e7ed6/flake.nix#L36>) (though this might still work as is, because HLS uses a wrapper to launch the correct version depending on the compiler version, but I haven't tested this; still, in the best case we would download a whole new version of HLS and never use it).

**Comment by dundalek** [comment]
Makes sense, I can see this being potentially useful. I also do 1. for example for `clojure-lsp`, last time I tried it it did not work well under nix-shell.

There can be also little details that might not work anyway like if the binary is packaged like `xyz-ls` instead of `xyz_ls`. I am not sure if the extra complexity in the plugin is worth it. By always getting it from nix we should be sure to specify the correct binary name.

I will probably not implement this myself, but will keep the issue open in case someone has additional feedback for motivation.
