### ISSUE TITLE
Support for Linters and Formatters

### ISSUE THREAD

**Issue by kenos1** [dundalek/lazy-lsp.nvim#25]
Hi,

I've been using this plugin for months and I'm enjoying it. It has changed how I use LSPs in Neovim, but I think that this plugin would be more useful if linters and formatters were included (since `nixpkgs` seems to have packages for them.) Thank you for your time making this plugin!

**Comment by dundalek** [comment]
Hi, could you give an example which linters/formatters do you have in mind? How would you expect to run them?

**Comment by kenos1** [comment]
I was thinking of the linters and formatters from null-ls.

**Comment by dundalek** [comment]
I see, that sounds useful. Although it makes sense to probably have a separate plugin since null-ls is likely to use different packages and a different mechanism how they are integrated.

I don't use null-ls myself (I prefer efm-langserver) so I don't plan to work on it. However, someone could take inspiration from lazy-lsp and create a similar plugin lazy-null-ls.

**Comment by kenos1** [comment]
efm-langserver looks pretty cool, but if we were to integrate nix-shell to it I think it would be a better fit for it to be a separate project.
