### ISSUE TITLE
Integrate none-ls builtins into curated defaults

### ISSUE THREAD

**Issue by fdietze** [dundalek/lazy-lsp.nvim#37]
This idea just popped up in my head.

For example, there are lots of formatters in `null-ls`, which don't have a language-server, but are useful on their own.

https://github.com/nvimtools/none-ls.nvim/tree/main/lua/null-ls/builtins

**Comment by dundalek** [comment]
Null-ls was mentioned before: https://github.com/dundalek/lazy-lsp.nvim/issues/25

I am not a fan of null-ls because it is limited only to neovim, which lowers leverage due to smaller ecosystem. Instead I prefer [efm-langserver](https://github.com/mattn/efm-langserver) because it can be used also from other editors and expands the ecosystem.

For example I use `shellcheck` integration with efm which is really nice, but these are more opinionated so it makes sense for users to set up them individually. Therefore I would consider it out of scope.

**Comment by fdietze** [comment]
I see. I hadn't dug that deep yet. Feel free to close.

**Comment by dundalek** [comment]
I've added an example of [using EFM](https://github.com/dundalek/lazy-lsp.nvim/commit/f9b68260ea89c3ccec4f80e0cc7f3774fce6f254) to docs, hope it helps.

If you have any other specific linter/formatter in mind, we could also add it there.
