### ISSUE TITLE
Provide callback for when LSP is setup

### ISSUE THREAD

**Issue by xyven1** [dundalek/lazy-lsp.nvim#42]
When settings up a server, sometimes one also wants to run some lua to update their neovim environment. This can be supported by allowing the config for a language server to be a table, or a function which returns a table, and is passed some context. This would provided much greater flexibility to the loading of servers.

**Comment by dundalek** [comment]
Could you provide a concrete example which specific language servers are you using and what are you trying to achieve?

**Comment by xyven1** [comment]
Sure. This is the functionality i would like to be able to use:
```lua
servers = {
  rust_analyzer = {
    settings = {
      ['rust-analyzer'] = {
        checkOnSave = {
          command = 'clippy',
        },
      }
    }
  },
  lua_ls = function()
    require('neodev').setup {}
    return {}
  end,
}
```

**Comment by dundalek** [comment]
Thanks for the example, it is always good to have a concrete use case at hand. I am trying to keep number of available options at minimum, trying to see if it is possible to use existing options first. For example many use cases can be achieved using existing lspconfig hooks like [on_new_config](https://github.com/dundalek/lazy-lsp.nvim/issues/31#issuecomment-2016424933).

In the case of `neodev`, it mentions in the README it needs to be setup before `lspconfig` is loaded.

I am not quite sure if it would even work the callback setup, because it might be too late since lazy-lsp would require the `lspconfig` internally by then.

My suggestion would be to try to configure it like:
```lua
require('neodev').setup { ... }
require('lazy-lsp').setup { ... }
```

**Comment by dundalek** [comment]
I am going to close the issue for now, we can revisit it in the future if a more compelling use case or reason comes up.
